version: '3'

networks:
    htpc_internal:
        # default driver
        driver: bridge
services:
    production-nginx:
        container_name: 'nginx'
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/proxy-control.conf:/etc/nginx/conf.d/proxy-control.conf
            - ./nginx/html:/var/www
            - ${DOCKER_VOLUME}/nginx/logs:/var/log/nginx
            - ${HOME}/htpc-letsencrypt/dh-param/dhparam-4096.pem:/etc/ssl/certs/dhparam-4096.pem
            - ${HOME}/htpc-letsencrypt/conf/live/dougie-fresh.xyz/fullchain.pem:/etc/letsencrypt/live/dougie-fresh.xyz/fullchain.pem
            - ${HOME}/htpc-letsencrypt/conf/live/dougie-fresh.xyz/privkey.pem:/etc/letsencrypt/live/dougie-fresh.xyz/privkey.pem
        networks:
            - htpc_internal

    plex:
        container_name: plex
        image: lscr.io/linuxserver/plex
        networks:
            - htpc_internal
        environment:
            - PLEX_CLAIM=${PLEX_CLAIM}
            - ADVERTISE_IP=${PLEX_ADVERTISE_IP}
            - PUID=${PUID}
            - PGID=${PGID}
            - VERSION=latest
        volumes:
            - ${DOCKER_VOLUME}/plex:/config
            - ${DOCKER_VOLUME}/plex/transcode:/transcode
            - ${MEDIA_HOME}/myrepo:${MEDIA_HOME}/myrepo
            - ${MEDIA_HOME}/dougie/mytoshiba1:${MEDIA_HOME}/mytoshiba1
            - ${MEDIA_HOME}/dougie/toshiba5tb:${MEDIA_HOME}/toshiba5tb
            - ${MEDIA_HOME}/easystore:${MEDIA_HOME}/easystore
            - ${BUFFALO_HOME}/media:${BUFFALO_HOME}/media
        ports:
            - '32400:32400'
            - '3005:3005'
            - '8324:8324'
            - '32469:32469'
            - '1900:1900/udp'
            - '32410:32410/udp'
            - '32412:32412/udp'
            - '32413:32413/udp'
            - '32414:32414/udp'
        restart: unless-stopped

    sabnzbd:
        container_name: sabnzbd
        image: lscr.io/linuxserver/sabnzbd
        # build: ./sabnzbd
        networks:
            - htpc_internal
        depends_on: 
            - production-nginx
        restart: unless-stopped
        volumes:
            - ${MEDIA_HOME}/mywd1:${MEDIA_HOME}/mywd1
            - ${MEDIA_HOME}/myrepo:${MEDIA_HOME}/myrepo
            - ${MEDIA_HOME}/dougie/mytoshiba1:${MEDIA_HOME}/mytoshiba1
            - ${MEDIA_HOME}/dougie/toshiba5tb:${MEDIA_HOME}/toshiba5tb
            - ${BUFFALO_HOME}/media:${BUFFALO_HOME}/media
            - ${MEDIA_HOME}/easystore:${MEDIA_HOME}/easystore
            - ${MEDIA_HOME}/mywd1/downloads:/downloads
            - ${DOCKER_VOLUME}/sabnzbd:/config
        ports:
            - 8888:8888
            - 9090:9090
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}

    radarr:
        container_name: radarr
        image: linuxserver/radarr
        depends_on: 
            - sabnzbd
            - production-nginx
        restart: unless-stopped
        volumes:
            - ${MEDIA_HOME}/mywd1:${MEDIA_HOME}/mywd1
            - ${MEDIA_HOME}/myrepo:${MEDIA_HOME}/myrepo
            - ${MEDIA_HOME}/dougie/mytoshiba1:${MEDIA_HOME}/mytoshiba1
            - ${MEDIA_HOME}/dougie/toshiba5tb:${MEDIA_HOME}/toshiba5tb
            - ${MEDIA_HOME}/easystore:${MEDIA_HOME}/easystore
            - ${BUFFALO_HOME}/media:${BUFFALO_HOME}/media
            - ${MEDIA_HOME}/mywd1/downloads:/downloads
            - ${DOCKER_VOLUME}/radarr:/config
        ports:
            - 7979:7979
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        networks:
            - htpc_internal

    sonarr:
        container_name: sonarr
        image: linuxserver/sonarr
        depends_on: 
            - sabnzbd
            - production-nginx
        restart: unless-stopped
        volumes:
            - ${MEDIA_HOME}/dougie/mytoshiba1:${MEDIA_HOME}/mytoshiba1
            - ${MEDIA_HOME}/dougie/toshiba5tb:${MEDIA_HOME}/toshiba5tb
            - ${MEDIA_HOME}/easystore:${MEDIA_HOME}/easystore
            - ${BUFFALO_HOME}/media:${BUFFALO_HOME}/media
            - ${MEDIA_HOME}/mywd1/downloads:/downloads
            - ${DOCKER_VOLUME}/sonarr:/config
        ports:
            - 8989:8989
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        networks:
            - htpc_internal

    ombi:
        container_name: ombi
        image: linuxserver/ombi
        depends_on: 
            - sabnzbd
            - production-nginx
        restart: unless-stopped
        volumes:
            - ${DOCKER_VOLUME}/ombi:/config
        ports:
            - 3579:3579
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        networks:
            - htpc_internal

    tautulli:
        container_name: plexpy
        image: linuxserver/tautulli
        depends_on: 
            - production-nginx
        restart: unless-stopped
        volumes:
          - ${DOCKER_VOLUME}/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
          - ${DOCKER_VOLUME}/plexpy:/config
        ports:
          - 18181:8181
        environment:
          - PUID=${PUID}
          - PGID=${PGID}
          - TZ=${TZ}
        networks:
          - htpc_internal

    organizr:
        container_name: organizr
        image: organizr/organizr
        restart: unless-stopped
        depends_on:
          - production-nginx
        ports:
          - 8899:80
        environment:
          - PUID=${PUID}
          - PGID=${PGID}
          - TZ=${TZ}
        volumes:
            - ${DOCKER_VOLUME}/organizr:/config
        networks:
          - htpc_internal

    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        restart: unless-stopped
        depends_on:
          - production-nginx
        ports:
          - 19000:9000
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${DOCKER_VOLUME}/portainer:/data
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/localtime:/etc/localtime:ro
        networks:
          - htpc_internal
