version: '3'

services:
    plex:
        container_name: plex
        image: linuxserver/plex
        network_mode: host
        environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - VERSION=latest
        volumes:
        - ${MEDIA_HOME}/mywd1/docker-volumes/plex:/config
        - ${MEDIA_HOME}/myrepo:${MEDIA_HOME}/myrepo
        - ${MEDIA_HOME}/mytoshiba1:${MEDIA_HOME}/mytoshiba1
        - ${MEDIA_HOME}/toshiba5tb:${MEDIA_HOME}/toshiba5tb
        - ${BUFFALO_HOME}/media:${BUFFALO_HOME}/media
        - ${MEDIA_HOME}/mywd1/docker-volumes/plex/transcode:/transcode
        restart: unless-stopped

    sabnzbd:
        container_name: sabnzbd
        image: ghcr.io/linuxserver/sabnzbd
        # build: ./sabnzbd
        depends_on: 
        - production-nginx
        restart: unless-stopped
        volumes:
        - ${MEDIA_HOME}/mywd1:${MEDIA_HOME}/mywd1
        - ${MEDIA_HOME}/myrepo:${MEDIA_HOME}/myrepo
        - ${MEDIA_HOME}/mytoshiba1:${MEDIA_HOME}/mytoshiba1
        - ${MEDIA_HOME}/toshiba5tb:${MEDIA_HOME}/toshiba5tb
        - ${BUFFALO_HOME}/media:${BUFFALO_HOME}/media
        - ${MEDIA_HOME}/mywd1/Downloads:/Downloads
        - ${DOCKER_VOLUME}/sabnzbd:/config
        ports:
        - 8888:8888
        - 9090:9090
        environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        networks:
            - dougie-fresh

    radarr:
        container_name: radarr
        image: linuxserver/radarr
        depends_on: 
        - sabnzbd
        - production-nginx
        restart: unless-stopped
        volumes:
        - ${MEDIA_HOME}/mywd1:${MEDIA_HOME}/mywd1
        - ${MEDIA_HOME}/myrepo:${MEDIA_HOME}/myrepo
        - ${MEDIA_HOME}/mytoshiba1:${MEDIA_HOME}/mytoshiba1
        - ${MEDIA_HOME}/toshiba5tb:${MEDIA_HOME}/toshiba5tb
        - ${BUFFALO_HOME}/media:${BUFFALO_HOME}/media
        - ${MEDIA_HOME}/mywd1/Downloads:/Downloads
        - ${DOCKER_VOLUME}/radarr:/config
        ports:
        - 7878:7878
        environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        networks:
            - dougie-fresh

    sonarr:
        container_name: sonarr
        image: linuxserver/sonarr
        depends_on: 
        - sabnzbd
        - production-nginx
        restart: unless-stopped
        volumes:
        - ${MEDIA_HOME}/mytoshiba1:${MEDIA_HOME}/mytoshiba1
        - ${MEDIA_HOME}/toshiba5tb:${MEDIA_HOME}/toshiba5tb
        - ${BUFFALO_HOME}/media:${BUFFALO_HOME}/media
        - ${MEDIA_HOME}/mywd1/Downloads:/Downloads
        - ${DOCKER_VOLUME}/sonarr:/config
        ports:
        - 8989:8989
        environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        networks:
            - dougie-fresh

    ombi:
        container_name: ombi
        image: linuxserver/ombi
        depends_on: 
        - sabnzbd
        - production-nginx
        restart: unless-stopped
        volumes:
        - ${DOCKER_VOLUME}/ombi:/config
        ports:
        - 3579:3579
        environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        networks:
            - dougie-fresh

    plexpy:
        container_name: plexpy
        image: linuxserver/plexpy
        depends_on: 
        - production-nginx
        restart: unless-stopped
        volumes:
          - ${DOCKER_VOLUME}/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
          - ${DOCKER_VOLUME}/plexpy:/config
        ports:
          - 18181:8181
        environment:
          - PUID=${PUID}
          - PGID=${PGID}
          - TZ=${TZ}
        networks:
          - dougie-fresh

    organizr:
        container_name: organizr
        image: lsiocommunity/organizr
        restart: unless-stopped
        ports:
          - 8899:8899
        environment:
          - PUID=${PUID}
          - PGID=${PGID}
          - TZ=${TZ}
        networks:
          - dougie-fresh

    portainer:
        image: portainer/portainer:latest
        container_name: portainer
        restart: unless-stopped
        depends_on:
          - production-nginx
        ports:
          - 19000:9000
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${DOCKER_VOLUME}/portainer:/data
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/localtime:/etc/localtime:ro
        networks:
          - dougie-fresh

            #    watchtower:
            #        container_name: watchtower
            #        #image: v2tec/watchtower
            #        image: containrrr/watchtower
            #        restart: unless-stopped
            #        volumes:
            #        - /var/run/docker.sock:/var/run/docker.sock
            #          #      - ${DOCKER_VOLUME}/watchtower/config.json:/config.json
            #        environment:
            #        - WATCHTOWER_CLEANUP=true
            #        - WATCHTOWER_NOTIFICATIONS=slack
            #        - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${SLACK_WEBHOOK}

    production-nginx:
        container_name: 'dougie-fresh-nginx'
        image: nginx:alpine
        restart: unless-stopped
        ports:
        - "80:80"
        - "443:443"
        volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/html:/var/www
        - ${DOCKER_VOLUME}/letsencrypt/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
        - ${DOCKER_VOLUME}/letsencrypt/conf/live/dougie-fresh.xyz/fullchain.pem:/etc/letsencrypt/live/dougie-fresh.xyz/fullchain.pem
        - ${DOCKER_VOLUME}/letsencrypt/conf/live/dougie-fresh.xyz/privkey.pem:/etc/letsencrypt/live/dougie-fresh.xyz/privkey.pem
        networks:
            - dougie-fresh
    
    #network_mode: "host"

networks:
    dougie-fresh:
        driver: bridge
