#!/bin/bash

usage() {
cat << HEREDOC
Usage: htpc-upgrade [-h] [-r]
    -h  display help
    -r  restart containers
HEREDOC
    exit 1
}

RESTART=""

while getopts hr opt; do
    case "${opt}" in
        h) usage
            ;;
        r) RESTART="true"
            ;;
        *) usage
            ;;
    esac
done

# Update images
echo "Pulling latest htpc images..."
docker-compose pull

if [[ ${RESTART} != "" ]]; then
    echo "Restarting containers..."
    # Restart docker containers using latest images
    docker-compose down && docker-compose up -d
fi

echo "done!"