#!/bin/bash

usage() {
cat << HEREDOC
Usage: htpc-upgrade [-h] [-r] [-b]
    -h  display help
    -r  restart containers
    -b  backup configuration
HEREDOC
    exit 1
}

RESTART=""
BACKUP=""

while getopts hrb opt; do
    case "${opt}" in
        h) usage
            ;;
        r) RESTART="true"
            ;;
        b) BACKUP="true"
            ;;
        *) usage
            ;;
    esac
done

if [[ ${BACKUP} != "" ]]; then
    echo "Backing up configuration (docker-volumes)"

    BACKUP_DATE=$(date +%A)
    BACKUP_FILENAME="docker-volumes-${BACKUP_DATE}.tar.gz"
    sudo tar czpf /home/dougie/buffalo/backup/docker-volumes/${BACKUP_FILENAME} /media/dougie/mywd1/docker-volumes
fi

# Update images
echo "Pulling latest htpc images..."
docker-compose pull

if [[ ${RESTART} != "" ]]; then
    echo "Restarting containers..."
    # Restart docker containers using latest images
    docker-compose down && docker-compose up -d
fi

echo "done!"