#!/usr/bin/env bash

logger "Checking for letsencrypt renewal..."
docker run -t --rm \
-v /home/dougie/htpc-letsencrypt/conf:/etc/letsencrypt \
-v /home/dougie/htpc-letsencrypt/lib:/var/lib/letsencrypt \
-v /home/dougie/htpc-letsencrypt/log:/var/log/letsencrypt \
-v /home/dougie/htpc/letsencrypt/html:/var/www \
certbot/certbot \
renew | logger && docker restart nginx

logger "Letsencrypt renew finished..."