#!/usr/bin/env bash

logger "Checking for letsencrypt renewal..."
docker run -t --rm \
-v /home/dougie/mywd1/docker-volumes/letsencrypt/conf:/etc/letsencrypt \
-v /home/dougie/mywd1/docker-volumes/var/lib/letsencrypt:/var/lib/letsencrypt \
-v /home/dougie/htpc/nginx/html:/var/www \
-v /home/dougie/mywd1/docker-volumes/var/log/letsencrypt:/var/log/letsencrypt \
certbot/certbot \
renew | logger && docker restart dougie-fresh-nginx

logger "Letsencrypt renew finished..."